import requests

url = 'http://localhost:5000/predict_api'
r = requests.post(url,json={'FRUITS_VEGGIES':1 ,'DAILY_STRESS':1 , 'PLACES_VISITED':1,  'CORE_CIRCLE':1,  'SUPPORTING_OTHERS':1,  'SOCIAL_NETWORK':1,  'ACHIEVEMENT':1,  'DONATION':1  ,'TODO_COMPLETED':1 , 'FLOW':1  ,'DAILY_STEPS':1  'LIVE_VISION':1,  'SLEEP_HOURS':1  ,'LOST_VACATION':1  ,'DAILY_SHOUTING':1,  'SUFFICIENT_INCOME':1,  'PERSONAL_AWARDS':1,  'TIME_FOR_PASSION':1  ,'WEEKLY_MEDITATION':1,  'AGE':1,  'GENDER':1})
print(r.json())